version: "3"
services:
  airflow:
    build:
      context: ./
      dockerfile: Dockerfile.airflow
    image: airflowimage
    container_name: DiamondPredictionAirflow
    ports:
      - "8080:8080"
  
  flaskapp:
    build:
      context: ./
      dockerfile: Dockerfile.flask
    image: flaskimage
    container_name: FlaskApp
    ports:
      - "5000:5000"
    