name: Python application

on:
  push:
    branches: [ "main" ]
    paths-ignore:
        - 'README.md'  
  pull_request:
    branches: [ "main" ]
    paths-ignore:
        - 'README.md'  

permissions:
  contents: read

jobs:
  build:

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: pytest
    - name: Docker compose up
      run: docker-compose up